### ISSUE TITLE
Hot rebuilds not working in `npm run dev`

### ISSUE THREAD

**Issue by veronicamarie24** [proteinjs/proteinjs#6]
Webpack is building, but the build doesn't get shipped to the client
![Screenshot 2024-05-11 at 5 28 07 PM](https://github.com/proteinjs/proteinjs/assets/22463012/09e484c2-c406-4030-9658-a1d6c8332982)

Workaround is to run `npm run build` for the ui code

**Comment by brentbahry** [comment]
[fix: reactApp adds hot client build bundle names explicitly as script tags when hot client builds are enabled](https://github.com/proteinjs/server/commit/a585f9040587dae550c76c24827dfefc4af55127)
